import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../component/Header";
import Page from "./connect/page";
import { Geist, Geist_Mono, M_PLUS_Rounded_1c } from "next/font/google";
import Footer from "../component/Footer";


const mPlusRounded = M_PLUS_Rounded_1c({
  variable: "--font-m-plus-rounded",
  subsets: ["latin"],
  weight: "100",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Universal Health Care",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
      
      className={`${geistSans.variable} ${geistMono.variable} ${mPlusRounded.variable} antialiased`}
      >
     <Page/>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
